### ISSUE TITLE
KeyError: 'scan_interval_fast'

### ISSUE THREAD

**Issue by lazi3b0y** [eriknn/ha-pax_ble#18]
Hey, updated to the latest version a few days ago and noticed this in the logs today along with the fans not being setup in HA

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pax_ble/__init__.py", line 30, in async_setup_entry
    scan_interval_fast = config_entry.data[CONF_SCAN_INTERVAL_FAST]
KeyError: 'scan_interval_fast'

(Running Home Assistant 2023.3.0)

Any ideas? :)

**Comment by eriknn** [comment]
https://github.com/eriknn/ha-pax_ble/issues/17

**Comment by lazi3b0y** [comment]
> #17
> 
> I’ll try to use automatic version control in config flow the next time - that should help avoid breaking stuff like this.

Ah, cool, it work after removing them and adding them again, as you said :) Thx! 
No worries, you're quick to respond/fix which I think is more important than not breaking things!
