### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by lazi3b0y** [eriknn/ha-pax_ble#3]
Hello there :)

To be honest I'm not entirely sure if its this integration that is the problem, but I figured I'd start here..
Anyway, it seems like I'm unable to integrate my PAX fans after the latest home assistant update 2022.10.
The only thing I'm getting it "Connection failed".

**Comment by eriknn** [comment]
I know, I have the same issue. I have it with other BT integrations as well, assuming it’s a bug in the HA update!

**Comment by lazi3b0y** [comment]
I logged the exception that is thrown and got this:

'HaBleakScannerWrapper' object has no attribute 'find_device_by_address'

Doesn't tell me much since I'm not very used to python. I'll just leave it here, in case it helps in any way :)

**Comment by eriknn** [comment]
Yeah, I checked and found the same! There’s been a breaking change there, so I’ll update my code when I find time!

**Comment by eriknn** [comment]
Try it now!

I've had so much issues with this way to connect, and now realized the mac should be passed uppercase and not lowercase...

**Comment by lazi3b0y** [comment]
Ah cool will try again tonight! :)

**Comment by lazi3b0y** [comment]
Seems to be working again, nice! :D
