### ISSUE TITLE
Feature request: Manual Override

### ISSUE THREAD

**Issue by MedicoreV8** [eriknn/ha-pax_ble#30]
Maybe I don't quite understand the functionality of the settings, but I'm looking for two options that are not in the integration now.
So I guess this can be considered as a feature request.

I want to be able to manually start/stop the FAN through the integration and manually override the RPM of the fan.
This could be done by adding 1 switch, like a dimmable lightbulb but only with RPM setting. 0 = off, 2400RPM = full power.

I have the Vent-Axia SVARA. I've only connected Live and Neutral.

**Comment by eriknn** [comment]
You can use trickle mode on/off and trickle speed?

**Comment by MedicoreV8** [comment]
I manually added it using the MAC-address and the pincode.
It added 26 sensors, none of which are tricke mode on/of and trickle speed. I do have Trickledays Weekdays and Trickledays Weekends but I have no idea what those actually do. Trickleday is not in my vocabulary and it doesn't translate to a dutch word that makes sense.

I only have Boost mode, automatic cycles, Sensitivity Humidity and Sensitivity Light.
Somehow it requires a combination of those settings to get the fan to stop spinning.

**Comment by eriknn** [comment]
Trickle means permanent «low speed» ventilation. Can be set for and weekends. Just like in the app.

**Comment by MedicoreV8** [comment]
The Mode is set to "Draft Shutter Mode"
Did I set this somehow? Can I change it? What are the options?

**Comment by eriknn** [comment]
I think you chose this the first time you set up the fan - at least I remember doing some choices the first time.
The folling modes are possible:
"MultiMode", "DraftShutterMode", "WallSwitchExtendedRuntimeMode", "WallSwitchNoExtendedRuntimeMode"
, "HeatDistributionMode"

I don't really know what the differences are. Mine is in "MultiMode".
