### ISSUE TITLE
Not showing in HACS

### ISSUE THREAD

**Issue by HenkeGoransson** [eriknn/ha-pax_ble#31]
Hi!
Good work with this custom component! It works great!

However, it is not showing up in HACS interface.
It works perfect to manually add it to HA.

**Comment by eriknn** [comment]
I think maybe you must add it as a custom repository?

**Comment by HenkeGoransson** [comment]
Yes!
Sorry, that is correct!
Usually they turn up automatically

**Comment by el97** [comment]
@eriknn I suggest that this repo should be included in the repo-store. The optimal thing would be if it was a default integration for Home Assistant but adding it to the HACS repo-store is a start. https://hacs.xyz/docs/publish/include
