### ISSUE TITLE
I can't add my vent axia svara fan

### ISSUE THREAD

**Issue by MarkP12345** [eriknn/ha-pax_ble#34]
Hi when I try to add my fan to home assistant using the ha-pax-ble I get the message: failed to connect (see picture, I deleted the mac and pincode after the failed to connect message). Is there something I can do about this? The log shows that he couldnt find the mac adress.  I used the mac adress which is on the device, next to the pin. And the mac adress is right (confirmed with a bluetooth app) Thanks! (btw this is not the same issue as #32, I dont use Shelly)
![Foto 02-01-2024 om 09 41](https://github.com/eriknn/ha-pax_ble/assets/155430378/983e96db-8725-4fb6-976f-b57e0351d5ff)

**Comment by Hedda** [comment]
> I can't add my vent axia svara fan

Does that "Vent-Axia Svara" fan use the same board and firmware internally as the "Pax Calima"?

I see that both Pax Electro Products AB and Vent-Axia are both part of Volution Group PLC,( and so is a few other doughter companies too), so it would make sense that they use the same hardware, but if so do they also use the exact same firmware?

https://www.vent-axia.com/range/lo-carbon-svara

https://pax.se/sv/produkt/calima/pax-calima-flakt

https://community.home-assistant.io/t/pax-calima/118489/

https://community.home-assistant.io/t/vent-axia-svara-app-controlled-extractor-fan/260082

**Comment by Prileyman** [comment]
Any luck in getting this fan to connect? I have the same issue

**Comment by MarkP12345** [comment]
I replaced my bleutooth dongle and used an extensioncable and that did the
trick.

Op di 6 feb 2024 00:29 schreef Prileyman ***@***.***>:

**Comment by Prileyman** [comment]
Now working. The MAC address on the label was incorrect. Once using a Bluetooth app to get the correct address, ensuring no other program was running and entering the address correctly (all lower case with colons) it connected! Phew

**Comment by Hedda** [comment]
> Now working. **The MAC address on the label was incorrect.** Once using a Bluetooth app to get the correct address, ensuring no other program was running and entering the address correctly (all lower case with colons) it connected!

@Prileyman recommend that you open a new issue for that with suggested possible solutions (like maybe converting/translating or force formatting of the MAC address) since your problem and solution might not be the same as the original poster.

**Comment by eriknn** [comment]
Added hint on mac-adress format, also improved format handling.
