### ISSUE TITLE
Added thru HACS but no config screen

### ISSUE THREAD

**Issue by GeoffMorg** [eriknn/ha-pax_ble#35]
I've successfully added the integration and he files are in custom components but when I click on the integration to configure it I get this screen.

![image](https://github.com/eriknn/ha-pax_ble/assets/47286307/fc0fa512-18eb-490c-bf5c-3cb91f41066c)

**Comment by eriknn** [comment]
I have no idea how you got to there - sure you disn’t press the wrong button somewhere?

**Comment by Cptkex82** [comment]
When you manually add it to hacs it doesnt show any text as per the screenshot. 

But that only for installation, the configuration is when you add the integration in devices and integrations in configuration. Install in hacs, restart and it should show up automatically in integrations ready to config

**Comment by GeoffMorg** [comment]
Ah OK, now I've got it. HACS is a very grey area for me!!

I was hoping it would find the device but no. So now I just need to pull the fan from the ceiling to get the MAC.

Thanks both

**Comment by Cptkex82** [comment]
My was automatically detected but you still need the pin code from inside.



Den lör 6 jan. 2024 10:40GeoffMorg ***@***.***> skrev:

**Comment by Quepali** [comment]
I also struggle finding any config. Can't find anything ha-pax or pax related anywhere. Cloned the code with terminal to custom_components\pax_ble and rebooted, but still nothing.

**Comment by eriknn** [comment]
«Add integration» -> «Pax Bluetooth»

**Comment by Quepali** [comment]
I got this searching now for the full name. Is this correct?
![image](https://github.com/eriknn/ha-pax_ble/assets/149523255/65522d51-8070-421a-b5b5-cf1462c94b0b)

**Comment by eriknn** [comment]
No. The integration seems to not be detected. Please verify that you put it in the correct location.

**Comment by Quepali** [comment]
This path looks a bit strange...
![image](https://github.com/eriknn/ha-pax_ble/assets/149523255/64a940d7-c745-4d41-8aaf-c89eb5c189b1)

Should all the files be under config/custom_components/pax_ble ? (as you can see I somehow got an extra custom_components/pax_ble in the path)

**Comment by eriknn** [comment]
You’re correct, that’s your issue.

**Comment by Quepali** [comment]
I suggest either not have the structure in the repo or adding a line to the documentation for when cloning. I don't know what the best solution is.

**Comment by eriknn** [comment]
Removing this structure would put the integration-files in the same folder as the github-readme etc, so that won't work. Seems that most developers do it the same as me,
Also feel that what is in the documentation already would be good enough for most people, so I'll close this with no changes.
