### ISSUE TITLE
Configuration resetting

### ISSUE THREAD

**Issue by Quepali** [eriknn/ha-pax_ble#37]
Got the Pax Calima up in Home Assistant now.
![image](https://github.com/eriknn/ha-pax_ble/assets/149523255/0fe65b39-5150-4ed5-b822-27d03c2d1c3f)

But somehow, whatever I change in the Configuration card in Home Assistant is automatically reset to default values.

The log card says something like "<konfiguration attribute> changed to <value and unit> by the service Choose: Select" 
(translation from Norwegian).

**Comment by eriknn** [comment]
What are you trying to select?

**Comment by eriknn** [comment]
Closed due to inactivity…
