### ISSUE TITLE
Release 1.0.0 creates duplicate entities

### ISSUE THREAD

**Issue by BigFriendlyDuck** [eriknn/ha-pax_ble#42]
Hi,

Just installed release v1.0.0 and ended up with duplicate entities all over.

The existing entity is greyed out and "no longer beieng provided by the pax_ble integration".
The new entity has gotten itself a new name, and breakes both dashboard and automations. 

![image](https://github.com/eriknn/ha-pax_ble/assets/45755307/ae068e64-3f61-4a74-82f8-83890f863ddc)

**Comment by eriknn** [comment]
See https://github.com/eriknn/ha-pax_ble/issues/40

Sorry for the hassle!
