### ISSUE TITLE
*IMPORTANT NOTE*

### ISSUE THREAD

**Issue by eriknn** [eriknn/ha-pax_ble#44]
As I have installed balanced ventilation in my home, I no longer need to use my Pax fan. This means that I no longer will be improving the integration. I *might* try to reply and fix any bugs that are reported, but I will no longer be able to test the code.

Hopefully somebody else will take over the development so that new fan models also can be supported in the future!

**Comment by audunru** [comment]
It seems to work OK as of august 2024. :-)

**Comment by el97** [comment]
No issues yet.

**Comment by ThomasPontoppidan** [comment]
Sorry to hear that! I have tried to add my fan but so far no luck. It doesn't auto discover and I can't add it manually either.

**Comment by eriknn** [comment]
Check the bluetooth integration / debugging. It should show you any discovered / availiable devices. If it’s not there then you have a problem. If it’s there it might be a range issue.

**Comment by aridder** [comment]
Works for me! Thank you for this.
