### ISSUE TITLE
Pax Bluetooth update v1.1.1b

### ISSUE THREAD

**Issue by zlakes01** [eriknn/ha-pax_ble#52]
There is a new update that I'm not able to run. 

![image](https://github.com/user-attachments/assets/160bb522-19eb-48c5-ada4-c97f06fb2695)

**Comment by eriknn** [comment]
Might be because it's a pre-release.
See https://github.com/eriknn/ha-pax_ble/issues/51

**Comment by eriknn** [comment]
Are you able to download the latest release?

**Comment by zlakes01** [comment]
Yes, this morrning.
