### ISSUE TITLE
Incorrect version (1.0.0) shown in the main configuration page?

### ISSUE THREAD

**Issue by texnic** [eriknn/ha-pax_ble#53]
After recent updates, HA > Settings > Devices and Services > PAX still shows 1.0.0. HA > HACS > Downloaded > Pax Bluetooth correctly shows 1.1.4. I guess some label not updated?

**Comment by eriknn** [comment]
Ah, probably shows the manifest.json version. While HACS shows the github release version. Fun to have this several places. Will try to remember next time, shouldn’t matter for now :)

**Comment by texnic** [comment]
Right, I was just wondering if I may have some strange installation. Cannot connect my Svensa with the current version. Will open another issue.

**Comment by eriknn** [comment]
Fixed on current release (but will probably forget again later)
